import sodium from "libsodium-wrappers-sumo";

import { initCrypto } from "./identity";

/**
 * The message envelope.
 *
 * `crypto_aead_xchacha20poly1305_ietf`, under the project key for an epoch.
 * XChaCha20 rather than ChaCha20 for the 192-bit nonce: at that size a random
 * nonce per message is safe without a counter, and a counter is a piece of
 * state that has to survive tab crashes, two devices, and being wrong once.
 *
 * ═══ What the associated data is for ═══
 *
 * The ciphertext is bound to WHERE it lives: channel, message id and epoch.
 * None of that is secret — the server stores all three in columns — but
 * authenticating it means the server cannot MOVE a message. Without it, a
 * ciphertext from a private channel can be re-inserted into one everybody
 * reads, and it decrypts perfectly, because nothing in the bytes says where it
 * came from.
 *
 * That is why the message id is generated by the client before encrypting
 * rather than by the database after: an id assigned afterwards cannot be
 * inside the thing it identifies.
 *
 * ═══ What this does not do ═══
 *
 * It does not hide who sent a message, when, or how long it was. Those are
 * columns and lengths, and pretending otherwise would be the kind of
 * half-claim this codebase keeps deleting. It hides the content.
 */

const ENVELOPE_VERSION = 1;

export interface MessageContext {
  channelId: string;
  messageId: string;
  epoch: number;
}

/**
 * The authenticated-but-not-encrypted header.
 *
 * Length-prefixed for the same reason the project-key signature is: naive
 * concatenation lets a byte move from the end of one field to the start of the
 * next without changing the bytes being authenticated.
 */
function associatedData(context: MessageContext): Uint8Array {
  const parts = [
    sodium.from_string(context.channelId),
    sodium.from_string(context.messageId),
    sodium.from_string(String(context.epoch)),
  ];

  const out = new Uint8Array(1 + parts.reduce((n, p) => n + 4 + p.length, 0));
  const view = new DataView(out.buffer);
  out[0] = ENVELOPE_VERSION;

  let off = 1;
  for (const part of parts) {
    view.setUint32(off, part.length, false);
    out.set(part, off + 4);
    off += 4 + part.length;
  }
  return out;
}

/** Seal a message. Returns `nonce ‖ ciphertext`, which is what gets stored. */
export async function sealMessage(
  plaintext: string,
  projectKey: Uint8Array,
  context: MessageContext,
): Promise<Uint8Array> {
  await initCrypto();

  const nonce = sodium.randombytes_buf(
    sodium.crypto_aead_xchacha20poly1305_ietf_NPUBBYTES,
  );
  const ciphertext = sodium.crypto_aead_xchacha20poly1305_ietf_encrypt(
    sodium.from_string(plaintext),
    associatedData(context),
    null,
    nonce,
    projectKey,
  );

  const out = new Uint8Array(nonce.length + ciphertext.length);
  out.set(nonce, 0);
  out.set(ciphertext, nonce.length);
  return out;
}

/**
 * Open a message, or throw.
 *
 * Throws rather than returning null so a caller cannot render an unopenable
 * message as an empty one. A message that will not open is either the wrong
 * epoch — recoverable, fetch the older key — or tampering. Both deserve to be
 * seen; neither deserves to look like a blank line in a conversation.
 */
export async function openMessage(
  sealed: Uint8Array,
  projectKey: Uint8Array,
  context: MessageContext,
): Promise<string> {
  await initCrypto();

  const nonceLen = sodium.crypto_aead_xchacha20poly1305_ietf_NPUBBYTES;
  if (sealed.length <= nonceLen) {
    throw new Error("This message is truncated.");
  }

  try {
    const plaintext = sodium.crypto_aead_xchacha20poly1305_ietf_decrypt(
      null,
      sealed.subarray(nonceLen),
      associatedData(context),
      sealed.subarray(0, nonceLen),
      projectKey,
    );
    return sodium.to_string(plaintext);
  } catch {
    throw new Error("This message could not be opened with that key.");
  }
}
