import { beforeAll, describe, expect, it } from "vitest";

import { initCrypto } from "./identity";
import { openMessage, sealMessage } from "./message";
import { createProjectKey } from "./project-key";

/**
 * The interesting assertions here are not "it round-trips". They are about the
 * associated data — the part that stops the SERVER moving a message it cannot
 * read into somewhere it should not be.
 */
describe("the message envelope", () => {
  let key: Uint8Array;
  let other: Uint8Array;
  const context = {
    channelId: "cccccccc-cccc-cccc-cccc-cccccccccccc",
    messageId: "11111111-2222-3333-4444-555555555555",
    epoch: 1,
  };

  beforeAll(async () => {
    await initCrypto();
    key = await createProjectKey();
    other = await createProjectKey();
  });

  it("opens what it sealed", async () => {
    const sealed = await sealMessage("meet at four", key, context);
    expect(await openMessage(sealed, key, context)).toBe("meet at four");
  });

  it("survives unicode without mangling it", async () => {
    // Messages are prose written by people, and κ, é and emoji all appear in
    // this product's own UI copy.
    const text = "κ = 0.62 — Ferreira agreed 🙂";
    const sealed = await sealMessage(text, key, context);
    expect(await openMessage(sealed, key, context)).toBe(text);
  });

  it("will not open under a different project key", async () => {
    const sealed = await sealMessage("meet at four", key, context);
    await expect(openMessage(sealed, other, context)).rejects.toThrow(
      /could not be opened/i,
    );
  });

  it("refuses a message moved to another channel", async () => {
    // THE ATTACK. The server cannot read this message, but without the
    // associated data it could re-insert the row into a channel everyone can
    // see, and it would decrypt perfectly for them.
    const sealed = await sealMessage("only for the leads", key, context);

    await expect(
      openMessage(sealed, key, {
        ...context,
        channelId: "dddddddd-dddd-dddd-dddd-dddddddddddd",
      }),
    ).rejects.toThrow(/could not be opened/i);
  });

  it("refuses a message given a different id", async () => {
    // Re-ordering or duplicating a conversation by copying one row over
    // another. The id is generated by the client precisely so it can be
    // authenticated — an id assigned by the database afterwards could not be
    // inside the thing it identifies.
    const sealed = await sealMessage("only for the leads", key, context);

    await expect(
      openMessage(sealed, key, {
        ...context,
        messageId: "99999999-9999-9999-9999-999999999999",
      }),
    ).rejects.toThrow(/could not be opened/i);
  });

  it("refuses a message relabelled to another epoch", async () => {
    const sealed = await sealMessage("only for the leads", key, context);
    await expect(openMessage(sealed, key, { ...context, epoch: 2 })).rejects.toThrow(
      /could not be opened/i,
    );
  });

  it("refuses a tampered ciphertext", async () => {
    const sealed = await sealMessage("meet at four", key, context);
    const tampered = new Uint8Array(sealed);
    const at = tampered.length - 1;
    tampered[at] = (tampered[at] ?? 0) ^ 0xff;

    await expect(openMessage(tampered, key, context)).rejects.toThrow(
      /could not be opened/i,
    );
  });

  it("refuses a truncated envelope with a message that says so", async () => {
    // Distinguishable from a wrong key, because the two need different
    // responses: one is corruption, the other is "fetch the older epoch".
    await expect(openMessage(new Uint8Array(8), key, context)).rejects.toThrow(
      /truncated/i,
    );
  });

  it("gives two identical messages different ciphertexts", async () => {
    // A random nonce per message. Identical ciphertexts would leak that two
    // messages are the same without decrypting either.
    const a = await sealMessage("ok", key, context);
    const b = await sealMessage("ok", key, context);
    expect(a).not.toEqual(b);
  });
});
