"use client";

import { PAPER_BUCKET } from "@Porcupine/shared";
import { useCallback, useEffect, useRef, useState } from "react";

import { Button, Input, Select } from "@/components/ui";
import { colourFor } from "@/lib/annotation-colour";
import { createClient } from "@/lib/supabase/client";
import { tidyRects } from "@/lib/highlight-rects";
import { rangeForPageText } from "@/lib/page-text";

// Generated by scripts/vendor-pdfjs.mjs from the installed pdfjs-dist. The
// text layer positions every run with inline custom properties that only mean
// anything alongside these rules; without them the spans stack at the origin
// and every selection lands in the wrong place.
import "@/styles/pdf-text-layer.css";

/** Format ISO timestamp for annotation display */
export function formatAnnotationTime(isoString?: string): { relative: string; full: string } {
  if (!isoString) return { relative: "", full: "" };
  const date = new Date(isoString);
  if (isNaN(date.getTime())) return { relative: "", full: "" };

  const now = Date.now();
  const diffSec = Math.max(0, Math.floor((now - date.getTime()) / 1000));

  let relative = "";
  if (diffSec < 60) relative = "Just now";
  else if (diffSec < 3600) relative = `${Math.floor(diffSec / 60)}m ago`;
  else if (diffSec < 86400) relative = `${Math.floor(diffSec / 3600)}h ago`;
  else if (diffSec < 604800) relative = `${Math.floor(diffSec / 86400)}d ago`;
  else relative = date.toLocaleDateString(undefined, { month: "short", day: "numeric" });

  const full = date.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  return { relative, full };
}

/**
 * The paper, drawn as the paper.
 *
 * Each page is a `<canvas>` with pdf.js's text layer laid over it: transparent
 * spans positioned on top of the glyphs, one per run. Selecting them is an
 * ordinary DOM selection, which is why highlighting works here at all and why
 * the anchoring engine needs no idea that any of this exists — the text inside
 * those spans is the same `getTextContent()` that produced `file_pages`.
 *
 * The bytes are fetched with the reader's own JWT rather than through a signed
 * URL. A signed URL is a bearer token: it has to be minted, timed, kept out of
 * logs and out of `Referer` (hazard B-10), and it grants whoever holds it
 * access regardless of membership. `download()` carries the session instead,
 * so the storage policy from stage 1 is evaluated per request and there is no
 * token to leak.
 */

/**
 * Room to the right of every page for the names.
 *
 * A label drawn at the end of its highlight lands in the middle of the
 * sentence whenever a passage ends mid-line, covering the words it is meant to
 * annotate. Margin notes go in the margin.
 */
const GUTTER = 148;

/** Enough for one line of the name chip, used to keep them from overlapping. */
const LABEL_HEIGHT = 18;

/** One page's live state. Kept out of React state deliberately — see below. */
interface PageSlot {
  /**
   * Paper PLUS gutter, and the positioning context for everything drawn.
   *
   * Highlight rectangles and name labels are both placed against this box, so
   * a label at `paperWidth + 8` lands in the margin instead of on the words.
   * Reserving the space by narrowing the paper alone does not work: the page
   * is centred, so free width splits evenly and half the gutter ends up on
   * the wrong side.
   */
  container: HTMLDivElement;
  /** The white page itself: canvas and text layer, nothing else. */
  paper: HTMLDivElement;
  /** Unscaled page size, so a zoom can resize the box without redrawing it. */
  baseWidth: number;
  baseHeight: number;
  canvas: HTMLCanvasElement;
  layer: HTMLDivElement;
  rendered: boolean;
  rendering: boolean;
}

export interface PdfHighlight {
  id: string;
  /** 1-based. */
  page: number;
  start: number;
  end: number;
  drifted: boolean;
  /** Whose mark this is — the colour is derived from it, not stored. */
  authorId: string;
  authorName: string;
  /**
   * Only ever true for the reader's own marks.
   *
   * A private annotation is filtered out by RLS before it leaves the database
   * — `annotations_select_visible` requires `visibility = 'PROJECT' OR
   * author_id = current_user_id()` — so another member's private note never
   * reaches this component at all. The flag is here to LABEL your own, not to
   * hide anybody else's, and nothing here may be allowed to become the thing
   * that enforces it.
   */
  isPrivate: boolean;
  body?: string | null;
  createdAt?: string;
  quote?: string;
  isMine?: boolean;
}

export function PdfDocument({
  storagePath,
  pageTexts,
  highlights,
  onSelection,
  onDeleteHighlight,
  focusPage,
}: {
  storagePath: string;
  /** The stored page strings, index 0 = page 1. Offsets are measured here. */
  pageTexts: string[];
  highlights: PdfHighlight[];
  /** Called after every selection change inside the document. */
  onSelection: () => void;
  /** Optional handler to delete user's own annotation from popup. */
  onDeleteHighlight?: (id: string) => void;
  /** Scroll this page into view once, when the document is ready. */
  focusPage: number | null;
}) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);
  const [zoom, setZoom] = useState(1);
  const [pageCount, setPageCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  // Read inside the render loop, which must not be rebuilt to change scale.
  const zoomRef = useRef(zoom);
  /** Set by the load effect, so zoom can ask for a redraw without owning one. */
  const rerenderRef = useRef<(() => void) | null>(null);
  const goToPageRef = useRef<((page: number) => void) | null>(null);
  const slotsRef = useRef<Map<number, PageSlot>>(new Map());
  const docRef = useRef<unknown>(null);
  // Read once, when the document is built. A later change of focus must not
  // rebuild the document out from under the reader.
  const focusPageRef = useRef(focusPage);
  const [status, setStatus] = useState<"loading" | "ready" | "failed">("loading");
  const [error, setError] = useState<string | null>(null);
  const [activeHighlight, setActiveHighlight] = useState<PdfHighlight | null>(null);
  const [popupPos, setPopupPos] = useState<{ top: number; left: number } | null>(null);

  /*
   * The latest highlights, without rebuilding the document to get them.
   *
   * `highlights` is derived in the parent with `.filter().map()`, so it is a
   * NEW ARRAY on every render — and the parent re-renders on every selection
   * change. Listing it as an effect dependency therefore tore down and rebuilt
   * every page each time the user dragged over a word, which is exactly the
   * "the page drifts away while I select" report: the scroll position belonged
   * to nodes that had just been replaced.
   *
   * So the document is built once per file, and painting reads through a ref.
   */
  const highlightsRef = useRef(highlights);

  const paintPage = useCallback((number: number, slot: PageSlot) => {
    for (const mark of slot.container.querySelectorAll(
      "[data-highlight], [data-highlight-author]",
    )) {
      mark.remove();
    }
    if (!slot.rendered) return;

    const box = slot.container.getBoundingClientRect();
    /** Where each name wants to go, before they are made not to collide. */
    const wanted: Array<{ highlight: PdfHighlight; top: number }> = [];

    for (const highlight of highlightsRef.current) {
      if (highlight.page !== number) continue;

      /*
       * Reconstructed from the stored character range, not from anything
       * remembered about where it was drawn last time. If the range no longer
       * fits the text on screen this returns null and nothing is drawn —
       * which is the honest outcome, because a rectangle in approximately the
       * right place is exactly the lie the anchoring engine exists to prevent.
       */
      const range = rangeForPageText(slot.layer, highlight.start, highlight.end);
      if (!range) continue;

      const colour = colourFor(highlight.authorId);
      const rects = tidyRects(Array.from(range.getClientRects()));

      for (const rect of rects) {
        const mark = document.createElement("div");
        mark.dataset.highlight = highlight.id;
        mark.dataset.author = highlight.authorId;
        mark.className = "pointer-events-none absolute rounded-[1px]";
        mark.style.left = `${rect.left - box.left}px`;
        mark.style.top = `${rect.top - box.top}px`;
        mark.style.width = `${rect.right - rect.left}px`;
        mark.style.height = `${rect.bottom - rect.top}px`;

        /*
         * Multiplied, not laid over.
         *
         * A translucent fill painted OVER the canvas darkens everything
         * beneath it, glyphs included, so marking a sentence made it harder to
         * read — the opposite of a highlighter. Multiply is what a real one
         * does: white paper × colour = colour, dark ink × colour ≈ dark ink.
         *
         * It also keeps the property this fill was chosen for: two people
         * marking the same sentence multiply into a third, darker colour, so
         * an overlap still reads as an overlap.
         */
        mark.style.background = colour.fill;
        mark.style.mixBlendMode = "multiply";

        // Drift keeps its own signal, and it has to survive being coloured by
        // author: a dotted underline rather than a different fill.
        if (highlight.drifted) {
          mark.style.borderBottom = `2px dotted ${colour.ink}`;
        }
        // Your own private notes, marked as such for you alone. Nobody else
        // receives them, so this is a reminder rather than a control.
        if (highlight.isPrivate) {
          mark.style.outline = `1px dashed ${colour.solid}`;
          mark.style.outlineOffset = "1px";
        }

        slot.container.append(mark);
      }

      const first = rects[0];
      if (first) wanted.push({ highlight, top: first.top - box.top });
    }

    /*
     * Names in the margin, stacked so they cannot cover each other.
     *
     * Two people marking the same sentence is the case the colours exist for,
     * and it put their names at identical coordinates — one legible, one
     * underneath it. Sorted by where their passage starts, then each pushed
     * down to clear the one above.
     *
     * A label is never pulled UP to its ideal spot once pushed, because that
     * would let a later, shorter passage jump above an earlier one and break
     * the correspondence between vertical order on the page and vertical
     * order in the margin.
     */
    wanted.sort((a, b) => a.top - b.top);
    let floor = -Infinity;

    for (const { highlight, top } of wanted) {
      const colour = colourFor(highlight.authorId);
      const at = Math.max(top, floor);
      floor = at + LABEL_HEIGHT + 2;

      const tag = document.createElement("button");
      tag.type = "button";
      tag.dataset.highlightAuthor = highlight.id;
      tag.textContent = highlight.isPrivate
        ? `${highlight.authorName} · private`
        : highlight.authorName;

      /*
       * Theme colours, not the highlight's.
       *
       * The label sits in the margin, on the APPLICATION's background rather
       * than on the page — so `ink` on a translucent `fill`, which is legible
       * over white paper, resolved dark-on-dark in dark mode and vanished.
       * The chip takes its surface from the theme and wears the author's hue
       * as an edge, which reads either way.
       */
      tag.className =
        "text-fine text-ink bg-raised pointer-events-auto cursor-pointer select-none absolute overflow-hidden " +
        "text-ellipsis whitespace-nowrap rounded-r-lg px-2 py-0.5 leading-tight shadow-sm hover:shadow-md " +
        "hover:bg-subtle active:scale-95 transition-all text-left border-l-[3px]";
      tag.style.borderLeftColor = colour.solid;
      tag.style.left = `${slot.paper.clientWidth + 10}px`;
      tag.style.top = `${at}px`;
      tag.style.maxWidth = `${GUTTER - 18}px`;
      tag.title = `Click to view note by ${highlight.authorName}`;

      tag.onclick = (e) => {
        e.stopPropagation();
        const rect = tag.getBoundingClientRect();
        const POPUP_WIDTH = 340;
        let left = rect.left - POPUP_WIDTH - 12;
        if (left < 16) {
          left = Math.min(window.innerWidth - POPUP_WIDTH - 16, rect.right + 12);
        }
        if (left < 16) {
          left = Math.max(16, (window.innerWidth - POPUP_WIDTH) / 2);
        }
        const top = Math.max(16, Math.min(rect.top - 10, window.innerHeight - 380));
        setPopupPos({ top, left });
        setActiveHighlight(highlight);
      };

      slot.container.append(tag);
    }
  }, []);

  /*
   * Zoom resizes every page and redraws the ones on screen.
   *
   * `--total-scale-factor`, the canvas bitmap and every run's font size are
   * all expressed in the scale, so a page drawn at the old one is wrong in
   * three ways at once — and its highlights' rectangles are in the old scale
   * until the text layer is rebuilt.
   *
   * The two halves are split on cost. Resizing the boxes is arithmetic and
   * happens for all of them, because leaving off-screen pages at their old
   * width makes the scrollbar describe a document that no longer exists and a
   * jump to page 200 land somewhere else. Redrawing bitmaps is the expensive
   * half and stays lazy: the observer asks for each page as it is reached.
   */
  useEffect(() => {
    zoomRef.current = zoom;
    const slots = slotsRef.current;
    if (slots.size === 0) return;

    const width = (rootRef.current?.clientWidth ?? 0) - GUTTER;

    for (const slot of slots.values()) {
      slot.rendered = false;
      slot.layer.replaceChildren();
      for (const drawn of slot.container.querySelectorAll(
        "[data-highlight], [data-highlight-author]",
      )) {
        drawn.remove();
      }

      const scale = (Math.max(width, 200) / slot.baseWidth) * zoom;
      slot.paper.style.width = `${slot.baseWidth * scale}px`;
      slot.container.style.width = `${slot.baseWidth * scale + GUTTER}px`;
    }

    rerenderRef.current?.();
  }, [zoom]);

  // Repaint in place when the annotations change — no rebuild, no scroll jump.
  useEffect(() => {
    highlightsRef.current = highlights;
    for (const [number, slot] of slotsRef.current) paintPage(number, slot);
  }, [highlights, paintPage]);

  /*
   * Pages are built with the DOM, not with React.
   *
   * pdf.js writes directly into the canvas and the text layer, and a re-render
   * that replaced those nodes would throw away work that costs tens of
   * milliseconds a page and, worse, invalidate a selection the user is in the
   * middle of making. React owns the frame; pdf.js owns what is inside it.
   *
   * Depends on the file alone. Everything that changes more often than the
   * file is read through a ref.
   */
  useEffect(() => {
    let cancelled = false;
    const slots = slotsRef.current;
    let observer: IntersectionObserver | null = null;

    async function load() {
      const supabase = createClient();
      const { data, error: downloadError } = await supabase.storage
        .from(PAPER_BUCKET)
        .download(storagePath);

      if (cancelled) return;
      if (downloadError || !data) {
        setStatus("failed");
        setError("The PDF could not be downloaded.");
        return;
      }

      const pdfjs = await import("pdfjs-dist");
      pdfjs.GlobalWorkerOptions.workerSrc = "/pdfjs/pdf.worker.min.mjs";

      const task = pdfjs.getDocument({
        data: new Uint8Array(await data.arrayBuffer()),
        // Vendored by scripts/vendor-pdfjs.mjs. Absent, a document using the
        // standard fonts draws substituted glyphs and a CID-keyed one draws
        // nothing — with no error to explain either.
        standardFontDataUrl: "/pdfjs/standard_fonts/",
        cMapUrl: "/pdfjs/cmaps/",
        cMapPacked: true,
      });

      let doc;
      try {
        doc = await task.promise;
      } catch {
        if (!cancelled) {
          setStatus("failed");
          setError("That PDF could not be opened.");
        }
        return;
      }

      if (cancelled) {
        await task.destroy();
        return;
      }

      docRef.current = doc;
      setPageCount(doc.numPages);
      setStatus("ready");

      const root = rootRef.current;
      if (!root) return;

      /*
       * Every page gets a placeholder at its true size immediately, and its
       * bitmap only when it comes near the viewport.
       *
       * Sizing the placeholders up front is what makes the scrollbar honest
       * and keeps a jump to page 200 from landing somewhere else once the
       * pages above it finish measuring. Rendering all of them is not an
       * option — a 300-page paper at this scale is hundreds of megabytes of
       * canvas, which is a tab that dies rather than a document that scrolls.
       */
      observer = new IntersectionObserver(
        (entries) => {
          for (const entry of entries) {
            if (!entry.isIntersecting) continue;
            const number = Number((entry.target as HTMLElement).dataset.page);
            void renderPage(number);
            // Which page you are on, for the "go to page" control to agree
            // with. `isIntersecting` fires for pages near the viewport too, so
            // the topmost visible one wins rather than the last to fire.
            if (entry.intersectionRatio > 0) {
              setCurrentPage((shown) =>
                entry.boundingClientRect.top <= (scrollRef.current?.clientHeight ?? 0) / 2
                  ? number
                  : shown,
              );
            }
          }
        },
        // The container, not the viewport: the document scrolls inside its
        // own window now, so the viewport never learns that page 40 arrived.
        { root: scrollRef.current, rootMargin: "1200px 0px" },
      );

      for (let number = 1; number <= doc.numPages; number++) {
        const page = await doc.getPage(number);
        if (cancelled) return;
        const viewport = page.getViewport({ scale: 1 });
        page.cleanup();

        /*
         * The page number, outside the text layer.
         *
         * A reader cites pages, and a canvas does not say which one it is. It
         * sits outside the layer on purpose: anything inside would be counted
         * by the offset walker and shift every anchor on the page by its
         * length.
         */
        const label = document.createElement("p");
        label.textContent = `Page ${number}`;
        label.className = "text-muted text-fine mb-1.5 text-center tabular-nums";

        const container = document.createElement("div");
        container.dataset.page = String(number);
        container.className = "relative mx-auto mb-8";

        const paper = document.createElement("div");
        // A page is paper: white in both themes, with a shadow that reads
        // against a light mat and a dark one.
        paper.className =
          "relative bg-white shadow-[0_2px_12px_rgba(0,0,0,0.18)] ring-1 ring-black/10";
        paper.style.aspectRatio = `${viewport.width} / ${viewport.height}`;

        const canvas = document.createElement("canvas");
        canvas.className = "block h-full w-full";

        const layer = document.createElement("div");
        // The attribute the selection code looks for. Identical to the plain
        // text reader's, so one capture function serves both.
        layer.dataset.sectionIndex = String(number - 1);
        layer.className = "textLayer";

        paper.append(canvas, layer);
        container.append(paper);
        root.append(label, container);
        slots.set(number, {
          container,
          paper,
          baseWidth: viewport.width,
          baseHeight: viewport.height,
          canvas,
          layer,
          rendered: false,
          rendering: false,
        });
        observer.observe(container);
      }

      rerenderRef.current = () => {
        for (const [number, slot] of slots) {
          const rect = slot.container.getBoundingClientRect();
          const view = scrollRef.current?.getBoundingClientRect();
          if (!view) continue;
          // Anything on screen or just off it, which is what the observer
          // would have asked for.
          if (rect.bottom > view.top - 800 && rect.top < view.bottom + 800) {
            void renderPage(number);
          }
        }
      };

      goToPageRef.current = (number) => {
        const slot = slots.get(number);
        if (!slot) return;
        slot.container.scrollIntoView({ block: "start", behavior: "smooth" });
        void renderPage(number);
      };

      if (focusPageRef.current) {
        slots.get(focusPageRef.current)?.container.scrollIntoView({ block: "center" });
        void renderPage(focusPageRef.current);
      } else {
        void renderPage(1);
      }
    }

    async function renderPage(number: number) {
      const slot = slots.get(number);
      const doc = docRef.current as { getPage: (n: number) => Promise<never> } | null;
      if (!slot || !doc || slot.rendered || slot.rendering) return;
      slot.rendering = true;

      try {
        const pdfjs = await import("pdfjs-dist");
        const page = (await doc.getPage(number)) as never as {
          getViewport: (o: { scale: number }) => { width: number; height: number };
          render: (o: Record<string, unknown>) => { promise: Promise<void> };
          getTextContent: () => Promise<unknown>;
          cleanup: () => void;
        };

        /*
         * Fit-to-width times the zoom.
         *
         * Measured on the FRAME rather than on the page container, because the
         * container's own width is what this is about to set — reading it back
         * would lock the page at whatever scale it was first drawn at and make
         * zoom a no-op after the first render.
         */
        const available = (rootRef.current?.clientWidth ?? 0) - GUTTER;
        const base = page.getViewport({ scale: 1 });
        const scale = (Math.max(available, 200) / base.width) * zoomRef.current;
        const viewport = page.getViewport({ scale });

        // The paper is the page; the container is the page plus its margin.
        slot.paper.style.width = `${viewport.width}px`;
        slot.container.style.width = `${viewport.width + GUTTER}px`;

        // Device pixel ratio, or the text is crisp and the page is not.
        const dpr = window.devicePixelRatio || 1;
        slot.canvas.width = Math.floor(viewport.width * dpr);
        slot.canvas.height = Math.floor(viewport.height * dpr);

        const context = slot.canvas.getContext("2d");
        if (!context) return;

        await page.render({
          canvas: slot.canvas,
          canvasContext: context,
          viewport,
          transform: dpr === 1 ? undefined : [dpr, 0, 0, dpr, 0, 0],
        }).promise;

        slot.layer.replaceChildren();

        /*
         * The scale the whole text layer is expressed in.
         *
         * `setLayerDimensions` CONSUMES `--total-scale-factor` — it writes
         * `width: round(down, var(--total-scale-factor) * 612px, …)` — but it
         * does not set it. pdf.js's own viewer sets it on the page container,
         * and this component is not that viewer, so nothing did.
         *
         * Unset, every calc() that depends on it collapses: the layer's width
         * and height become invalid, and each run's
         * `font-size: calc(var(--text-scale-factor) * var(--font-height))`
         * falls back to the browser's default 16px. Measured on a 9pt line:
         * the invisible text came out 460px wide over a canvas 720px wide,
         * so the selectable characters sat nowhere near the glyphs drawn
         * under them — and the error grew along the line, which is what
         * "the selection is not precise" and "not in a straight line" were.
         *
         * `--scale-round-x/y` are the rounding step that `round()` needs; they
         * are set by the viewer too, and 1px is what it uses.
         */
        slot.container.style.setProperty("--total-scale-factor", String(scale));
        slot.container.style.setProperty("--scale-round-x", "1px");
        slot.container.style.setProperty("--scale-round-y", "1px");

        pdfjs.setLayerDimensions(slot.layer, viewport as never);

        const textLayer = new pdfjs.TextLayer({
          textContentSource: (await page.getTextContent()) as never,
          container: slot.layer,
          viewport: viewport as never,
        });
        await textLayer.render();

        /*
         * The element that makes dragging across a page behave like dragging
         * across text.
         *
         * The runs are absolutely positioned, so a native selection between
         * two of them has nothing in between to travel through and the browser
         * picks its own path — which is the "selection comes out scrambled"
         * report. pdf.js solves this with a full-height blocker appended after
         * the runs: normally `inset: 100% 0 0` puts it below the text, and
         * while `.selecting` is set it covers the layer so the selection
         * extends smoothly to the end of the page.
         *
         * The CSS for it is in the rules we vendor. Only the ELEMENT and the
         * class toggle live in pdf.js's viewer, which this component does not
         * use — so both are recreated here, and without them the vendored
         * rules match nothing at all.
         */
        const end = document.createElement("div");
        end.className = "endOfContent";
        slot.layer.append(end);

        page.cleanup();
        slot.rendered = true;
        paintPage(number, slot);
      } catch {
        // A page that will not draw is left blank rather than taking the
        // document down. Its text layer is absent too, so nothing can be
        // selected from a page nobody can see.
      } finally {
        slot.rendering = false;
      }
    }

    void load();

    return () => {
      cancelled = true;
      observer?.disconnect();
      for (const slot of slots.values()) {
        slot.container.previousElementSibling?.remove();
        slot.container.remove();
      }
      slots.clear();
      rerenderRef.current = null;
      goToPageRef.current = null;
      const doc = docRef.current as { destroy?: () => Promise<void> } | null;
      void doc?.destroy?.();
      docRef.current = null;
    };
  }, [storagePath, paintPage]);

  /*
   * `.selecting`, for the duration of a drag.
   *
   * Added on pointerdown in the layer and removed globally on pointerup —
   * globally because a drag very often ends outside the page it began on, and
   * a layer left in the selecting state keeps its blocker over the text.
   */
  useEffect(() => {
    const clear = () => {
      for (const slot of slotsRef.current.values()) {
        slot.layer.classList.remove("selecting");
      }
    };
    document.addEventListener("pointerup", clear);
    return () => document.removeEventListener("pointerup", clear);
  }, []);

  const beginSelecting = useCallback((event: React.PointerEvent) => {
    const layer = (event.target as HTMLElement).closest?.(".textLayer");
    layer?.classList.add("selecting");
  }, []);

  const handleSelection = useCallback(() => onSelection(), [onSelection]);

  useEffect(() => {
    if (!activeHighlight) return;
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setActiveHighlight(null);
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [activeHighlight]);

  return (
    <div className="relative">
      {status === "ready" && (
        <div className="border-border bg-raised/95 backdrop-blur-md sticky top-0 z-10 mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border px-4 py-2.5 shadow-sm">
          {/* Page navigation */}
          <label className="text-muted text-fine flex items-center gap-2 font-medium">
            <span>Page</span>
            <Input
              compact
              type="number"
              min={1}
              max={pageCount}
              value={currentPage}
              onChange={(event) => {
                const wanted = Number(event.target.value);
                if (!Number.isFinite(wanted) || wanted < 1) return;
                const clamped = Math.min(Math.max(1, wanted), pageCount);
                setCurrentPage(clamped);
                goToPageRef.current?.(clamped);
              }}
              aria-label="Go to page"
              className="w-16 text-center tabular-nums font-semibold"
            />
            <span className="tabular-nums text-muted">of {pageCount}</span>
          </label>

          {/* Fine-tuning Zoom Controls */}
          <div className="flex flex-wrap items-center gap-2">
            <div className="flex items-center gap-1.5">
              <button
                type="button"
                onClick={() =>
                  setZoom((z) => Math.max(0.25, Math.round((z - 0.1) * 100) / 100))
                }
                disabled={zoom <= 0.25}
                aria-label="Zoom out"
                title="Zoom out (10%)"
                className="border-border text-ink hover:bg-surface flex size-8 items-center justify-center rounded-lg border text-base font-semibold shadow-xs disabled:opacity-40 transition-colors"
              >
                −
              </button>

              <label className="text-muted text-fine flex items-center gap-1 font-medium">
                <Input
                  compact
                  type="number"
                  min={25}
                  max={300}
                  step={5}
                  value={Math.round(zoom * 100)}
                  onChange={(event) => {
                    const val = Number(event.target.value);
                    if (Number.isFinite(val) && val >= 25 && val <= 300) {
                      setZoom(Math.round(val) / 100);
                    }
                  }}
                  aria-label="Zoom percentage"
                  className="w-16 text-center tabular-nums font-semibold"
                />
                <span className="tabular-nums text-muted">%</span>
              </label>

              <button
                type="button"
                onClick={() =>
                  setZoom((z) => Math.min(3, Math.round((z + 0.1) * 100) / 100))
                }
                disabled={zoom >= 3}
                aria-label="Zoom in"
                title="Zoom in (10%)"
                className="border-border text-ink hover:bg-surface flex size-8 items-center justify-center rounded-lg border text-base font-semibold shadow-xs disabled:opacity-40 transition-colors"
              >
                +
              </button>
            </div>

            {/* Quick Presets Dropdown */}
            <Select
              compact
              value={Math.round(zoom * 100)}
              onChange={(e) => setZoom(Number(e.target.value) / 100)}
              aria-label="Zoom preset"
            >
              <option value={50}>50%</option>
              <option value={75}>75%</option>
              <option value={90}>90%</option>
              <option value={100}>100% (Fit Width)</option>
              <option value={125}>125%</option>
              <option value={150}>150%</option>
              <option value={175}>175%</option>
              <option value={200}>200%</option>
              <option value={250}>250%</option>
              <option value={300}>300%</option>
              {![50, 75, 90, 100, 125, 150, 175, 200, 250, 300].includes(
                Math.round(zoom * 100),
              ) && (
                <option value={Math.round(zoom * 100)}>
                  {Math.round(zoom * 100)}% (Custom)
                </option>
              )}
            </Select>

            {zoom !== 1 && (
              <button
                type="button"
                onClick={() => setZoom(1)}
                className="text-primary hover:underline text-fine px-1.5 py-1 font-medium transition-colors cursor-pointer"
                title="Reset zoom to 100%"
              >
                Reset
              </button>
            )}
          </div>
        </div>
      )}

      {status === "loading" && (
        <p className="text-muted text-ui py-8 text-center">Opening the PDF…</p>
      )}
      {status === "failed" && (
        <p className="text-danger text-ui py-8 text-center">
          {error} You can still download it from the link above.
        </p>
      )}

      <div
        ref={scrollRef}
        data-testid="pdf-scroll"
        className="bg-surface h-[min(84vh,1100px)] overflow-auto px-4 py-6"
      >
        <div
          ref={rootRef}
          onPointerDown={beginSelecting}
          onMouseUp={handleSelection}
          onKeyUp={handleSelection}
          data-testid="pdf-document"
          data-pages={pageTexts.length}
        />
      </div>

      {/* Note Details Popup */}
      {activeHighlight && popupPos && (
        <div
          data-testid="annotation-popup"
          className="fixed z-50 animate-in fade-in zoom-in-95 duration-150"
          style={{
            top: `${popupPos.top}px`,
            left: `${popupPos.left}px`,
            width: "min(340px, calc(100vw - 32px))",
          }}
        >
          {/* Backdrop overlay for dismissing */}
          <div
            className="fixed inset-0 -z-10 bg-black/25 backdrop-blur-[1px]"
            onClick={() => setActiveHighlight(null)}
          />

          <div className="bg-raised border-border rounded-2xl border p-4 shadow-2xl ring-1 ring-black/5 flex flex-col gap-3">
            {/* Header */}
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-center gap-2">
                <span
                  aria-hidden="true"
                  className="size-3.5 shrink-0 rounded-full shadow-sm"
                  style={{ background: colourFor(activeHighlight.authorId).solid }}
                />
                <div>
                  <h4 className="text-ink text-ui font-semibold leading-none">
                    {activeHighlight.authorName}
                  </h4>
                  {activeHighlight.createdAt && (
                    <p className="text-muted text-fine mt-1 leading-tight">
                      {formatAnnotationTime(activeHighlight.createdAt).full}
                    </p>
                  )}
                </div>
              </div>

              <div className="flex items-center gap-1.5">
                {activeHighlight.isPrivate && (
                  <span className="border-border text-muted text-fine rounded-md border px-1.5 py-0.5 text-[11px]">
                    Private
                  </span>
                )}
                <button
                  type="button"
                  onClick={() => setActiveHighlight(null)}
                  className="text-muted hover:text-ink hover:bg-subtle rounded-lg p-1 transition-colors text-ui leading-none"
                  aria-label="Close note popup"
                >
                  ✕
                </button>
              </div>
            </div>

            {/* Quoted passage */}
            {activeHighlight.quote && (
              <div className="border-border/80 bg-subtle/50 rounded-xl border p-2.5">
                <p className="text-muted text-fine font-medium mb-1">
                  Page {activeHighlight.page} highlight:
                </p>
                <blockquote
                  className="text-ink text-fine line-clamp-4 border-l-2 pl-2 italic"
                  style={{ borderColor: colourFor(activeHighlight.authorId).solid }}
                >
                  “{activeHighlight.quote}”
                </blockquote>
              </div>
            )}

            {/* Note Body */}
            <div>
              {activeHighlight.body ? (
                <div>
                  <p className="text-muted text-fine font-medium mb-1">Note:</p>
                  <p className="text-ink text-ui whitespace-pre-wrap rounded-xl bg-surface/60 p-2.5 border border-border/50">
                    {activeHighlight.body}
                  </p>
                </div>
              ) : (
                <p className="text-muted text-fine italic bg-subtle/30 rounded-lg p-2 text-center">
                  Highlight only (no attached note)
                </p>
              )}
            </div>

            {/* Actions */}
            <div className="flex items-center justify-between gap-2 pt-2 border-t border-border/60">
              {activeHighlight.isMine && onDeleteHighlight ? (
                <Button
                  variant="danger"
                  className="text-fine"
                  onClick={() => {
                    const id = activeHighlight.id;
                    setActiveHighlight(null);
                    onDeleteHighlight(id);
                  }}
                >
                  Delete
                </Button>
              ) : (
                <span />
              )}
              <Button
                variant="ghost"
                className="text-fine"
                onClick={() => setActiveHighlight(null)}
              >
                Close
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
