#!/usr/bin/env node
/**
 * Emit the SQL needed to bring the local database up to schema.prisma.
 *
 * The migration split (docs/06-phase-0-build-plan.md):
 *   - Prisma owns the schema — schema.prisma is the source of truth for
 *     tables, columns, and indexes.
 *   - Supabase owns what actually ran — the files in supabase/migrations/.
 *   - This script is the bridge between them.
 *
 * `prisma migrate dev` is NEVER run against Supabase: it knows nothing about
 * policies, roles, or extensions and will cheerfully drop them.
 *
 * The diff is taken from the LIVE local database rather than by replaying the
 * migration history, because the history contains hand-written SQL (RLS
 * policies, generated columns, grants) that Prisma cannot model. Comparing
 * against the real database is the only comparison that reflects reality.
 *
 * Usage:
 *   pnpm db:diff                 # print the SQL
 *   pnpm db:diff --write <name>  # write supabase/migrations/<ts>_<name>.sql
 *
 * The emitted SQL is a STARTING POINT, not a finished migration. Every new
 * table still needs, by hand:
 *   - `alter table … enable row level security` + `force row level security`
 *   - policies (CI fails the merge if a public table has neither)
 *   - grants to Porcupine_app
 * See docs/01-data-model.md §5.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const repoRoot = join(pkgRoot, "..", "..");

// Prisma 7 no longer loads .env itself; Node 24 does it natively.
try {
  process.loadEnvFile(join(repoRoot, ".env"));
} catch {
  // Absent in CI, where the URL is already exported.
}

// prisma.config.ts resolves this into the datasource; checked here only so the
// failure is a sentence rather than a Prisma stack trace.
if (!(process.env.DIRECT_URL ?? process.env.DATABASE_URL)) {
  console.error(
    "DIRECT_URL (or DATABASE_URL) is not set.\n" +
    "Start the local stack with `pnpm db:start` first — the diff is taken\n" +
    "against the running database, not against the migration history.",
  );
  process.exit(1);
}

let sql;
try {
  sql = execFileSync(
    "prisma",
    [
      "migrate",
      "diff",
      // Prisma 7 removed --from-url; the live database is reached through the
      // datasource in prisma.config.ts, which resolves DIRECT_URL.
      "--from-config-datasource",
      "--to-schema",
      join(pkgRoot, "prisma", "schema.prisma"),
      "--script",
    ],
    { cwd: pkgRoot, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] },
  );
} catch {
  process.exit(1);
}

// Prisma emits this comment and nothing else when the database already matches.
const empty = sql
  .split("\n")
  .every((line) => line.trim() === "" || line.trim().startsWith("--"));

if (empty) {
  console.error("No drift: the database already matches schema.prisma.");
  process.exit(0);
}

const writeIndex = process.argv.indexOf("--write");
if (writeIndex === -1) {
  process.stdout.write(sql);
  console.error(
    "\n-- Printed only. Re-run with `--write <name>` to create a migration file.\n" +
    "-- Remember: RLS, policies, and grants are still yours to add by hand.",
  );
  process.exit(0);
}

const name = process.argv[writeIndex + 1];
if (!name || name.startsWith("--")) {
  console.error("--write needs a name, e.g. `pnpm db:diff --write corpus_schema`");
  process.exit(1);
}

// Match the timestamp format Supabase uses: YYYYMMDDHHMMSS.
const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
const target = join(repoRoot, "supabase", "migrations", `${stamp}_${name}.sql`);

writeFileSync(
  target,
  `-- Generated by \`pnpm db:diff --write ${name}\` from schema.prisma.\n` +
  `-- RLS policies and grants below this block are hand-written and are the\n` +
  `-- actual security boundary. Do not regenerate this file in place.\n\n` +
  sql,
);
console.error(`Wrote ${target.replace(`${repoRoot}/`, "")}`);
