-- ═══════════════════════════════════════════════════════════════════════════
-- Account deletion.
--
-- ─ Why the row survives ────────────────────────────────────────────────────
--
-- `screening_decisions.decided_by` references this table, and "who excluded
-- these forty papers, and when" has to keep having an answer a year later.
-- That single sentence is the argument for the whole product being defensible,
-- so deletion anonymises the row instead of removing it: email, display name,
-- avatar, ORCID, affiliation and every key column are scrubbed, and the
-- decisions keep pointing at a row that no longer identifies anybody.
--
-- It is pseudonymisation, not erasure, and /dpa says so in those words.
--
-- ─ The ten foreign keys ────────────────────────────────────────────────────
--
-- Ten columns held a user id with NO foreign key at all: annotations.author_id,
-- extractions.extractor_id and .verified_by, project_works.added_by and
-- .assignee_id, projects.created_by, project_keys.wrapped_by,
-- project_members.invited_by, file_objects.owner_id, saved_searches.created_by.
--
-- That is worse than a missing constraint usually is. A `delete from users`
-- did not FAIL on these — it succeeded, and left ten columns pointing at a row
-- that no longer existed. Nothing would have reported it. The screens that
-- join through them would simply have started returning nothing, which reads
-- as "no annotations yet" rather than as corruption.
--
-- RESTRICT where the column is required, SET NULL where it is optional. The
-- point of adding them now is not this migration — the deletion path here
-- never deletes the row — it is the next person who reaches for DELETE and is
-- stopped by the database rather than by a code review.
-- ═══════════════════════════════════════════════════════════════════════════

-- Generated by `pnpm db:diff --write account_deletion` from schema.prisma.
-- RLS policies and grants below this block are hand-written and are the
-- actual security boundary. Do not regenerate this file in place.

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "deleted_at" TIMESTAMPTZ(3),
ADD COLUMN     "deletion_scheduled_at" TIMESTAMPTZ(3);

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_keys" ADD CONSTRAINT "project_keys_wrapped_by_fkey" FOREIGN KEY ("wrapped_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_searches" ADD CONSTRAINT "saved_searches_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "file_objects" ADD CONSTRAINT "file_objects_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_works" ADD CONSTRAINT "project_works_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_works" ADD CONSTRAINT "project_works_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_extractor_id_fkey" FOREIGN KEY ("extractor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "annotations" ADD CONSTRAINT "annotations_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;



-- ═══════════════════════════════════════════════════════════════════════════
-- A project must keep an owner.
--
-- Nothing stopped the last one leaving. `removeMember` sets `removed_at` with
-- no check, RLS only gates the statement to OWNER or ADMIN, and `updateMemberRole`
-- can demote an owner the same way — so an admin could orphan a project, and
-- account deletion would have done it by accident on every sole-owned project
-- somebody closed their account on.
--
-- In the database rather than in the action, because there are two code paths
-- into it today (removal and demotion) and the deletion flow would have been a
-- third. A rule enforced in three places is a rule enforced in two of them.
--
-- The check runs only when the row was an OWNER and has stopped being one, so
-- it costs nothing on the ordinary update — touching a contributor's digest
-- cadence does not count owners.
-- ═══════════════════════════════════════════════════════════════════════════

create or replace function public.enforce_project_keeps_an_owner()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  -- Was an active owner, and is no longer one.
  if not (OLD.access_role = 'OWNER' and OLD.removed_at is null) then
    return NEW;
  end if;
  if NEW.access_role = 'OWNER' and NEW.removed_at is null then
    return NEW;
  end if;

  if not exists (
    select 1 from public.project_members pm
    where pm.project_id = OLD.project_id
      and pm.id <> OLD.id
      and pm.access_role = 'OWNER'
      and pm.removed_at is null
  ) then
    raise exception
      'This project would be left with no owner. Make somebody else an owner first.'
      using errcode = 'check_violation';
  end if;

  return NEW;
end;
$$;

comment on function public.enforce_project_keeps_an_owner() is
  'Refuses the removal or demotion of a project''s last remaining owner.';

revoke execute on function public.enforce_project_keeps_an_owner() from public;

create trigger project_members_keep_an_owner
  before update on public.project_members
  for each row execute function public.enforce_project_keeps_an_owner();

-- DELETE as well as UPDATE. `removeMember` soft-removes, but the table has a
-- delete policy for admins and nothing above would have covered it.
create or replace function public.enforce_project_keeps_an_owner_on_delete()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if not (OLD.access_role = 'OWNER' and OLD.removed_at is null) then
    return OLD;
  end if;

  -- The project going away takes its members with it, and that is not a
  -- project left without an owner. Without this check a cascade from
  -- `delete from projects` would raise instead.
  if not exists (select 1 from public.projects p where p.id = OLD.project_id) then
    return OLD;
  end if;

  if not exists (
    select 1 from public.project_members pm
    where pm.project_id = OLD.project_id
      and pm.id <> OLD.id
      and pm.access_role = 'OWNER'
      and pm.removed_at is null
  ) then
    raise exception
      'This project would be left with no owner. Make somebody else an owner first.'
      using errcode = 'check_violation';
  end if;

  return OLD;
end;
$$;

revoke execute on function public.enforce_project_keeps_an_owner_on_delete() from public;

create trigger project_members_keep_an_owner_on_delete
  before delete on public.project_members
  for each row execute function public.enforce_project_keeps_an_owner_on_delete();
