-- ═══════════════════════════════════════════════════════════════════════════
-- The PRISMA 2020 numbers this application cannot count.
--
-- The flow diagram has boxes for things no instrumentation here would know:
-- how many records an automation tool marked ineligible, how many reports were
-- sought from a library and never arrived, how many studies were found by
-- chasing citations rather than by searching. Those happen outside the app.
--
-- They are still required. A diagram with those boxes blank is not submittable
-- to a journal; a diagram with them silently zeroed asserts that no report
-- failed retrieval, which is a claim nobody checked. So they are entered by a
-- person, stored here, and drawn in the same figure as the counted ones — with
-- the page saying which is which, and this table recording who last said so.
--
-- Every column is NULLABLE and that is the design. Null means "we have not
-- said" and renders as a dash; zero means "we checked, and it was none".
-- Collapsing the two is precisely the error this table exists to prevent.
-- ═══════════════════════════════════════════════════════════════════════════

-- Generated by `pnpm db:diff --write prisma_manual_counts` from schema.prisma.
-- RLS policies and grants below this block are hand-written and are the
-- actual security boundary. Do not regenerate this file in place.

-- CreateTable
CREATE TABLE "prisma_manual_counts" (
    "project_id" UUID NOT NULL,
    "registers_identified" INTEGER,
    "automation_ineligible" INTEGER,
    "other_removed_before" INTEGER,
    "reports_sought" INTEGER,
    "reports_not_retrieved" INTEGER,
    "other_websites" INTEGER,
    "other_organisations" INTEGER,
    "other_citation_searching" INTEGER,
    "other_reports_sought" INTEGER,
    "other_reports_not_retrieved" INTEGER,
    "other_reports_assessed" INTEGER,
    "other_reports_excluded" INTEGER,
    "other_studies_included" INTEGER,
    "reports_of_included_studies" INTEGER,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "updated_by" UUID NOT NULL,

    CONSTRAINT "prisma_manual_counts_pkey" PRIMARY KEY ("project_id")
);

-- AddForeignKey
ALTER TABLE "prisma_manual_counts" ADD CONSTRAINT "prisma_manual_counts_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "prisma_manual_counts" ADD CONSTRAINT "prisma_manual_counts_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ── Row level security ─────────────────────────────────────────────────────
--
-- Readable by any member, writable only by the roles that can change what the
-- review asserts. These numbers go into a published figure: a contributor
-- screening papers has no reason to edit them, and an observer certainly does
-- not.
--
-- No DELETE policy. Clearing a number is setting it back to null, which is an
-- update; removing the row would lose `updated_by` and leave no record that
-- anybody ever entered anything.

alter table public.prisma_manual_counts enable row level security;
alter table public.prisma_manual_counts force row level security;

create policy prisma_manual_counts_select_member on public.prisma_manual_counts
  for select
  using (public.is_project_member(project_id));

create policy prisma_manual_counts_insert_admin on public.prisma_manual_counts
  for insert
  with check (
    public.has_project_role(project_id, array['OWNER','ADMIN']::"AccessRole"[])
    and updated_by = public.current_user_id()
  );

create policy prisma_manual_counts_update_admin on public.prisma_manual_counts
  for update
  using (public.has_project_role(project_id, array['OWNER','ADMIN']::"AccessRole"[]))
  with check (
    public.has_project_role(project_id, array['OWNER','ADMIN']::"AccessRole"[])
    and updated_by = public.current_user_id()
  );

grant select, insert, update on public.prisma_manual_counts to Porcupine_app;

comment on table public.prisma_manual_counts is
  'PRISMA 2020 figures that cannot be derived from recorded rows, entered by a '
  'person. Null means unstated and renders as a dash; zero means none.';
