-- Generated by `pnpm db:diff --write extraction_schema` from schema.prisma.
-- RLS policies and grants below this block are hand-written and are the
-- actual security boundary. Do not regenerate this file in place.

-- CreateEnum
CREATE TYPE "FieldType" AS ENUM ('TEXT', 'LONG_TEXT', 'NUMBER', 'BOOLEAN', 'ENUM', 'MULTI_ENUM', 'DATE', 'QUOTE', 'CITATION', 'URL');

-- CreateEnum
CREATE TYPE "ExtractionStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'IN_CONFLICT', 'RECONCILED', 'VERIFIED');

-- CreateEnum
CREATE TYPE "ExtractionOrigin" AS ENUM ('HUMAN', 'ASSISTED');

-- CreateTable
CREATE TABLE "protocols" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "dual_extract" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "protocols_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "protocol_fields" (
    "id" UUID NOT NULL,
    "protocol_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "type" "FieldType" NOT NULL,
    "options" JSONB,
    "required" BOOLEAN NOT NULL DEFAULT false,
    "requires_anchor" BOOLEAN NOT NULL DEFAULT false,
    "help_text" TEXT,
    "order" INTEGER NOT NULL,
    "question_id" UUID,

    CONSTRAINT "protocol_fields_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "extractions" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "project_work_id" UUID NOT NULL,
    "protocol_id" UUID NOT NULL,
    "extractor_id" UUID NOT NULL,
    "status" "ExtractionStatus" NOT NULL DEFAULT 'DRAFT',
    "origin" "ExtractionOrigin" NOT NULL DEFAULT 'HUMAN',
    "reconciled_from" UUID[],
    "verified_by" UUID,
    "submitted_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "extractions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "extraction_values" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "extraction_id" UUID NOT NULL,
    "field_id" UUID NOT NULL,
    "value" JSONB NOT NULL,
    "value_text" TEXT,
    "anchor_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "extraction_values_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "protocols_project_id_is_active_idx" ON "protocols"("project_id", "is_active");

-- CreateIndex
CREATE UNIQUE INDEX "protocols_project_id_name_version_key" ON "protocols"("project_id", "name", "version");

-- CreateIndex
CREATE INDEX "protocol_fields_protocol_id_order_idx" ON "protocol_fields"("protocol_id", "order");

-- CreateIndex
CREATE UNIQUE INDEX "protocol_fields_protocol_id_key_key" ON "protocol_fields"("protocol_id", "key");

-- CreateIndex
CREATE INDEX "extractions_project_id_status_idx" ON "extractions"("project_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "extractions_project_work_id_protocol_id_extractor_id_key" ON "extractions"("project_work_id", "protocol_id", "extractor_id");

-- CreateIndex
CREATE INDEX "extraction_values_project_id_idx" ON "extraction_values"("project_id");

-- CreateIndex
CREATE UNIQUE INDEX "extraction_values_extraction_id_field_id_key" ON "extraction_values"("extraction_id", "field_id");

-- AddForeignKey
ALTER TABLE "protocols" ADD CONSTRAINT "protocols_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "protocol_fields" ADD CONSTRAINT "protocol_fields_protocol_id_fkey" FOREIGN KEY ("protocol_id") REFERENCES "protocols"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "protocol_fields" ADD CONSTRAINT "protocol_fields_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_project_work_id_fkey" FOREIGN KEY ("project_work_id") REFERENCES "project_works"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_protocol_id_fkey" FOREIGN KEY ("protocol_id") REFERENCES "protocols"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extraction_values" ADD CONSTRAINT "extraction_values_extraction_id_fkey" FOREIGN KEY ("extraction_id") REFERENCES "extractions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extraction_values" ADD CONSTRAINT "extraction_values_field_id_fkey" FOREIGN KEY ("field_id") REFERENCES "protocol_fields"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extraction_values" ADD CONSTRAINT "extraction_values_anchor_id_fkey" FOREIGN KEY ("anchor_id") REFERENCES "anchors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

