-- Generated by `pnpm db:diff --write add_drive_folder_id` from schema.prisma.
-- RLS policies and grants below this block are hand-written and are the
-- actual security boundary. Do not regenerate this file in place.

-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "drive_folder_id" TEXT;

