-- Generated by `pnpm db:diff --write corpus_schema` from schema.prisma.
-- RLS policies and grants below this block are hand-written and are the
-- actual security boundary. Do not regenerate this file in place.

-- CreateEnum
CREATE TYPE "ScreenStatus" AS ENUM ('IDENTIFIED', 'SCREENING', 'INCLUDED', 'EXCLUDED', 'READING', 'EXTRACTED', 'SYNTHESIZED');

-- CreateEnum
CREATE TYPE "ReadStatus" AS ENUM ('NOT_STARTED', 'SKIMMED', 'READ', 'REREAD');

-- CreateEnum
CREATE TYPE "Residency" AS ENUM ('R2_SHARED', 'R2_USER', 'DEVICE_ONLY');

-- CreateEnum
CREATE TYPE "UploadState" AS ENUM ('PENDING', 'COMPLETE', 'ORPHANED');

-- CreateEnum
CREATE TYPE "TextStatus" AS ENUM ('PENDING', 'EXTRACTED', 'FAILED', 'NOT_APPLICABLE');

-- CreateEnum
CREATE TYPE "ScanStatus" AS ENUM ('PENDING', 'CLEAN', 'INFECTED', 'FAILED');

-- CreateEnum
CREATE TYPE "AnchorStatus" AS ENUM ('OK', 'DRIFTED', 'BROKEN');

-- CreateEnum
CREATE TYPE "AnnotationKind" AS ENUM ('HIGHLIGHT', 'NOTE', 'QUESTION', 'TODO');

-- CreateEnum
CREATE TYPE "AnnotationVisibility" AS ENUM ('PRIVATE', 'PROJECT');

-- CreateTable
CREATE TABLE "questions" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "parent_id" UUID,
    "order" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "keywords" TEXT[],
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "works" (
    "id" UUID NOT NULL,
    "doi" TEXT,
    "arxiv_id" TEXT,
    "openalex_id" TEXT,
    "pmid" TEXT,
    "title_norm" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "abstract" TEXT,
    "authors" JSONB NOT NULL,
    "venue" TEXT,
    "published_year" INTEGER,
    "published_on" TIMESTAMPTZ(3),
    "type" TEXT,
    "language" TEXT,
    "oa_status" TEXT,
    "oa_pdf_url" TEXT,
    "cited_by_count" INTEGER NOT NULL DEFAULT 0,
    "referenced_works" TEXT[],
    "concepts" JSONB,
    "citation_key" TEXT,
    "version_of_id" UUID,
    "fetched_at" TIMESTAMPTZ(3),
    "raw" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    -- HAND-EDITED. Prisma emitted a plain `tsvector` column because it cannot
    -- express generated columns; the generation expression below is the point
    -- of the column and is the reason this file is not regenerated in place.
    --
    -- R-14: language-aware via build_tsvector, never `to_tsvector('english')`.
    -- Title outranks abstract, so a title match sorts above a passing mention.
    "search_tsv" tsvector GENERATED ALWAYS AS (
      setweight(public.build_tsvector("language", "title"), 'A') ||
      setweight(public.build_tsvector("language", "abstract"), 'B')
    ) STORED,

    CONSTRAINT "works_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "saved_searches" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "query" JSONB NOT NULL,
    "cadence" "DigestCadence" NOT NULL DEFAULT 'WEEKLY',
    "last_run_at" TIMESTAMPTZ(3),
    "seen_work_ids" UUID[],
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "saved_searches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "file_objects" (
    "id" UUID NOT NULL,
    "owner_id" UUID NOT NULL,
    "project_id" UUID,
    "work_id" UUID,
    "bucket" TEXT NOT NULL,
    "storage_path" TEXT NOT NULL,
    "etag" TEXT,
    "residency" "Residency" NOT NULL DEFAULT 'R2_USER',
    "content_hash" TEXT,
    "oa_verified" BOOLEAN NOT NULL DEFAULT false,
    "upload_state" "UploadState" NOT NULL DEFAULT 'PENDING',
    "mime_type" TEXT NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "sha256" TEXT NOT NULL,
    "page_count" INTEGER,
    "text_status" "TextStatus" NOT NULL DEFAULT 'PENDING',
    "scan_status" "ScanStatus" NOT NULL DEFAULT 'PENDING',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "file_objects_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_works" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "work_id" UUID NOT NULL,
    "added_by" UUID NOT NULL,
    "source" TEXT NOT NULL,
    "screen_status" "ScreenStatus" NOT NULL DEFAULT 'IDENTIFIED',
    "exclude_reason" TEXT,
    "read_status" "ReadStatus" NOT NULL DEFAULT 'NOT_STARTED',
    "priority" INTEGER NOT NULL DEFAULT 0,
    "relevance_score" DOUBLE PRECISION,
    "assignee_id" UUID,
    "due_at" TIMESTAMPTZ(3),
    "reading_pct" INTEGER NOT NULL DEFAULT 0,
    "tags" TEXT[],
    "note" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "project_works_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_work_questions" (
    "project_work_id" UUID NOT NULL,
    "question_id" UUID NOT NULL,
    "relevance" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "project_work_questions_pkey" PRIMARY KEY ("project_work_id","question_id")
);

-- CreateTable
CREATE TABLE "anchors" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "file_id" UUID,
    "page" INTEGER,
    "quote" TEXT NOT NULL,
    "prefix" TEXT,
    "suffix" TEXT,
    "start_off" INTEGER,
    "end_off" INTEGER,
    "rects" JSONB,
    "section" TEXT,
    "status" "AnchorStatus" NOT NULL DEFAULT 'OK',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "anchors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "annotations" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "project_work_id" UUID NOT NULL,
    "anchor_id" UUID NOT NULL,
    "author_id" UUID NOT NULL,
    "kind" "AnnotationKind" NOT NULL DEFAULT 'HIGHLIGHT',
    "color" TEXT,
    "body" TEXT,
    "visibility" "AnnotationVisibility" NOT NULL DEFAULT 'PROJECT',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "annotations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "questions_project_id_idx" ON "questions"("project_id");

-- CreateIndex
CREATE UNIQUE INDEX "works_doi_key" ON "works"("doi");

-- CreateIndex
CREATE UNIQUE INDEX "works_arxiv_id_key" ON "works"("arxiv_id");

-- CreateIndex
CREATE UNIQUE INDEX "works_openalex_id_key" ON "works"("openalex_id");

-- CreateIndex
CREATE UNIQUE INDEX "works_pmid_key" ON "works"("pmid");

-- CreateIndex
CREATE UNIQUE INDEX "works_citation_key_key" ON "works"("citation_key");

-- CreateIndex
CREATE INDEX "works_title_norm_published_year_idx" ON "works"("title_norm", "published_year");

-- CreateIndex
CREATE INDEX "works_version_of_id_idx" ON "works"("version_of_id");

-- CreateIndex
CREATE INDEX "saved_searches_project_id_idx" ON "saved_searches"("project_id");

-- CreateIndex
CREATE INDEX "file_objects_owner_id_idx" ON "file_objects"("owner_id");

-- CreateIndex
CREATE INDEX "file_objects_project_id_idx" ON "file_objects"("project_id");

-- CreateIndex
CREATE INDEX "file_objects_content_hash_idx" ON "file_objects"("content_hash");

-- CreateIndex
CREATE INDEX "project_works_project_id_screen_status_idx" ON "project_works"("project_id", "screen_status");

-- CreateIndex
CREATE INDEX "project_works_assignee_id_idx" ON "project_works"("assignee_id");

-- CreateIndex
CREATE UNIQUE INDEX "project_works_project_id_work_id_key" ON "project_works"("project_id", "work_id");

-- CreateIndex
CREATE INDEX "project_work_questions_question_id_idx" ON "project_work_questions"("question_id");

-- CreateIndex
CREATE INDEX "anchors_project_id_idx" ON "anchors"("project_id");

-- CreateIndex
CREATE INDEX "anchors_file_id_page_idx" ON "anchors"("file_id", "page");

-- CreateIndex
CREATE INDEX "annotations_project_work_id_idx" ON "annotations"("project_work_id");

-- CreateIndex
CREATE INDEX "annotations_project_id_author_id_idx" ON "annotations"("project_id", "author_id");

-- CreateIndex
CREATE INDEX "annotations_anchor_id_idx" ON "annotations"("anchor_id");

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "questions_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "questions_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "works" ADD CONSTRAINT "works_version_of_id_fkey" FOREIGN KEY ("version_of_id") REFERENCES "works"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_searches" ADD CONSTRAINT "saved_searches_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "file_objects" ADD CONSTRAINT "file_objects_work_id_fkey" FOREIGN KEY ("work_id") REFERENCES "works"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "file_objects" ADD CONSTRAINT "file_objects_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_works" ADD CONSTRAINT "project_works_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_works" ADD CONSTRAINT "project_works_work_id_fkey" FOREIGN KEY ("work_id") REFERENCES "works"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_work_questions" ADD CONSTRAINT "project_work_questions_project_work_id_fkey" FOREIGN KEY ("project_work_id") REFERENCES "project_works"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_work_questions" ADD CONSTRAINT "project_work_questions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "anchors" ADD CONSTRAINT "anchors_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "anchors" ADD CONSTRAINT "anchors_file_id_fkey" FOREIGN KEY ("file_id") REFERENCES "file_objects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "annotations" ADD CONSTRAINT "annotations_project_work_id_fkey" FOREIGN KEY ("project_work_id") REFERENCES "project_works"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "annotations" ADD CONSTRAINT "annotations_anchor_id_fkey" FOREIGN KEY ("anchor_id") REFERENCES "anchors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

