-- ═══════════════════════════════════════════════════════════════════════════
-- Channels and messages — the first encrypted content in the product.
--
-- Messages are the right first surface for encryption and the roadmap says why:
-- append-only, no merge semantics, immediate value. There is no CRDT here and
-- no relay; a message is a row that never changes.
--
-- ── What the server can and cannot see ─────────────────────────────────────
--
-- CANNOT: the text of a message, and the name of a channel. Both are sealed
-- under the project key for an epoch, which the server never holds.
--
-- CAN, and this is stated rather than glossed: who wrote what, when, in which
-- channel, and roughly how long it was. Those are columns and lengths.
-- Encrypting content does not hide metadata, and a design that implied it did
-- would be making a promise it cannot keep.
--
-- ── Why the epoch is a column ──────────────────────────────────────────────
--
-- A message encrypted under epoch 3 stays encrypted under epoch 3 forever.
-- Rotation does not re-encrypt history — it cannot, since the server holds no
-- key — so every row must say which key opens it. A message that could not
-- name its epoch would be unreadable the moment anyone was removed from the
-- project.
--
-- ── Append-only, deliberately ──────────────────────────────────────────────
--
-- No UPDATE policy and no DELETE policy on either table, the same choice as
-- `project_keys`. An edited ciphertext is indistinguishable from a substituted
-- one, and "someone changed what they said and nothing recorded it" is a worse
-- property for a research conversation than "you cannot unsay it".
--
-- Deletion arrives when there is a retention story to attach it to, not before.
-- ═══════════════════════════════════════════════════════════════════════════

create table public.channels (
  -- No database default, and that is deliberate rather than an oversight: the
  -- channel id is authenticated as associated data alongside its encrypted
  -- name, so the client has to know it BEFORE encrypting. An id the database
  -- assigns afterwards cannot be inside the thing it identifies.
  id          uuid primary key,
  project_id  uuid not null
                references public.projects(id) on update cascade on delete cascade,
  -- Sealed like a message: the topic of a conversation is content.
  name_ct     bytea not null,
  epoch       integer not null,
  -- restrict, not cascade: a user row is never deleted out from under the
  -- things they authored, and matching Prisma's default for a required
  -- relation keeps `db:diff` quiet about a difference nobody chose.
  created_by  uuid not null
                references public.users(id) on update cascade on delete restrict,
  created_at  timestamptz(3) not null default current_timestamp,
  updated_at  timestamptz(3) not null
);

create index channels_project_id_idx on public.channels (project_id);

comment on column public.channels.name_ct is
  'The channel name, sealed under the project key for `epoch`. A server that '
  'could read channel names would know the shape of the work even without the '
  'messages.';

create table public.messages (
  id          uuid primary key,
  -- Denormalised so RLS can reach membership without joining channels on
  -- every row, matching how every other table in this schema is scoped.
  project_id  uuid not null
                references public.projects(id) on update cascade on delete cascade,
  channel_id  uuid not null
                references public.channels(id) on update cascade on delete cascade,
  author_id   uuid not null
                references public.users(id) on update cascade on delete restrict,
  epoch       integer not null,
  ciphertext  bytea not null,
  created_at  timestamptz(3) not null default current_timestamp
);

comment on column public.messages.id is
  'Generated by the CLIENT before encrypting, because it is authenticated as '
  'associated data. An id assigned by the database afterwards could not be '
  'inside the thing it identifies, and the server could then move a ciphertext '
  'between rows undetectably.';

create index messages_channel_id_created_at_idx
  on public.messages (channel_id, created_at);

alter table public.channels enable row level security;
alter table public.channels force row level security;
alter table public.messages enable row level security;
alter table public.messages force row level security;

-- ── channels ────────────────────────────────────────────────────────────────

create policy channels_select_member on public.channels
  for select
  using (public.is_project_member(project_id));

create policy channels_insert_member on public.channels
  for insert
  with check (
    public.is_project_member(project_id)
    and created_by = public.current_user_id()
  );

-- ── messages ────────────────────────────────────────────────────────────────
--
-- `author_id = current_user_id()` on insert is the half that matters: without
-- it a member could write a message attributed to a colleague, and since the
-- ciphertext is opaque nobody could tell from the content that they had.

create policy messages_select_member on public.messages
  for select
  using (public.is_project_member(project_id));

create policy messages_insert_author on public.messages
  for insert
  with check (
    public.is_project_member(project_id)
    and author_id = public.current_user_id()
    and exists (
      select 1
      from public.channels c
      where c.id = channel_id
        and c.project_id = messages.project_id
    )
  );

grant select, insert on public.channels to porcupine_app;
grant select, insert on public.messages to porcupine_app;
