-- How many papers each member is expected to extract.
--
-- No RLS work needed: this is a column on `projects`, which is already
-- protected, and the existing policies cover it. Only an owner or admin can
-- update a project row.
--
-- Nullable with no default, deliberately. A default of 25 would put a target
-- on every project ever created, including the thesis a single person is
-- writing, and "0 of 25" on a solo project is a reproach for no reason. Null
-- means the dashboard shows counts and no target at all.

-- Generated by `pnpm db:diff --write add_extraction_target` from schema.prisma.
-- RLS policies and grants below this block are hand-written and are the
-- actual security boundary. Do not regenerate this file in place.

-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "extraction_target" INTEGER;

