// Generated by scripts/build-latex-worker.mjs. Do not edit.
//
// The compiled worker's content hash, used to bust its URL. Committed
// rather than gitignored so a typecheck without a prior build still works.
export const WORKER_VERSION = "dbf054618272";
